steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'terraform'
    args: ['init']

    
  - id: 'terraform plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'terraform'
    args: ['plan']
    
  - id: 'terraform apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'terraform'
    args: ['apply --auto-approve']
