steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1:3:0'
    script: terraform init 
    
  - id:
    name: 'hashicorp/terraform:1:3:0'
    script: terraform plan
    
  - id:
    name: 'hashicorp/terraform:1:3:0'
    script: terraform apply --auto-approve
